### ISSUE TITLE
Cannot compile zlib

### ISSUE THREAD

**Issue by fumseckk** [madroach/ocaml-zlib#9] opened 2024-06-04 08:13 UTC
I'm having trouble installing `zlib` on an Arch machine.
Here is my output trying to `opam install zlib` :

```
The following actions will be performed:
  ∗ install zlib 0.6

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved zlib.0.6  (cached)
[ERROR] The compilation of zlib.0.6 failed at "dune build -p zlib".

#=== ERROR while compiling zlib.0.6 ===========================================#
# context     2.1.5 | linux/x86_64 | ocaml-base-compiler.5.1.0 | https://opam.ocaml.org#4e03b577
# path        ~/Desktop/prog/stage_l3/ocaml-mopsa-switch/_opam/.opam-switch/build/zlib.0.6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p zlib
# exit-code   1
# env-file    ~/.opam/log/zlib-11688-d7c8ca.env
# output-file ~/.opam/log/zlib-11688-d7c8ca.out
### output ###
# [...]
# /usr/include/string.h:43:39: note: expected ‘void * restrict’ but argument is of type ‘const char *’
#    43 | extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
#       |                      ~~~~~~~~~~~~~~~~~^~~~~~
# /home/phoenix/Desktop/prog/stage_l3/ocaml-mopsa-switch/_opam/lib/ocaml/caml/mlvalues.h:329:24: warning: passing argument 1 of ‘memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
#   329 | #define String_val(x) ((const char *) Bp_val(x))
#       |                       ~^~~~~~~~~~~~~~~~~~~~~~~~~
# zlib_stubs.c:409:12: note: in expansion of macro ‘String_val’
#   409 |     memcpy(String_val(tmp), header->comment, len);
#       |            ^~~~~~~~~~
# /usr/include/string.h:43:39: note: expected ‘void * restrict’ but argument is of type ‘const char *’
#    43 | extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
#       |                      ~~~~~~~~~~~~~~~~~^~~~~~



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build zlib 0.6
└─ 
╶─ No changes have been performed
```

I'm guessing the error should only be a warning and should not stop compilation, but it does.

**Comment by madroach** [comment] 2024-06-04 17:21
This is a duplicate of #8 and fixed since 0.7. Merging this into the opam repository is underway.

**Closed as completed by madroach** 2024-06-04 17:21 UTC
